# Generated by Django 2.2.4 on 2020-09-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coat_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=255)),
                ('examples', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('years', models.IntegerField(null=True)),
                ('months', models.IntegerField(null=True)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='app_one.Coat_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=30, null=True)),
                ('last', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.IntegerField(default=25)),
                ('off_schedule', models.IntegerField(default=5)),
                ('clean_feet', models.IntegerField(default=5)),
                ('short_haircut', models.IntegerField(default=10)),
                ('scissor_haircut', models.IntegerField(default=15)),
                ('special_handling', models.IntegerField(default=10)),
                ('shedless', models.IntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('bday', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app_one.Price_Book')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overdue', models.IntegerField(default=0)),
                ('special', models.IntegerField(default=0)),
                ('profuse', models.IntegerField(default=0)),
                ('dematting', models.IntegerField(default=0)),
                ('shedless', models.IntegerField(default=0)),
                ('service_price', models.IntegerField(default=0)),
                ('weight_price', models.IntegerField(null=True)),
                ('coat_price', models.IntegerField(null=True)),
                ('total', models.IntegerField(default=0)),
                ('on_schedule', models.BooleanField(default=True)),
                ('schedule_price', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='app_one.Dog')),
                ('estimate', models.ManyToManyField(related_name='quotes', to='app_one.Estimate')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='app_one.Owner')),
                ('price_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='app_one.Price_Book')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='app_one.Service')),
            ],
        ),
        migrations.AddField(
            model_name='estimate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='app_one.Owner'),
        ),
        migrations.AddField(
            model_name='dog',
            name='estimate',
            field=models.ManyToManyField(related_name='dogs', to='app_one.Estimate'),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='app_one.Owner'),
        ),
    ]
